### ISSUE TITLE
__consumer_offsets messages from Kafka 2.1+ not supported

### ISSUE THREAD

**Issue by simPod** [braedon/prometheus-kafka-consumer-group-exporter#28]
In previous version it reported lag per group (as also said in docs `kafka_consumer_group_lag{group, topic, partition}`)

Currently in 0.5, it only reports it per partition

`kafka_consumer_group_exporter_lag`

```
# HELP kafka_consumer_group_exporter_lag How far the exporter consumer is behind the head of a partition of the __consumer_offsets topic.
# TYPE kafka_consumer_group_exporter_lag gauge
kafka_consumer_group_exporter_lag{partition="7"} 1.0
kafka_consumer_group_exporter_lag{partition="8"} 1.0
kafka_consumer_group_exporter_lag{partition="9"} 1.0
kafka_consumer_group_exporter_lag{partition="13"} 1.0
kafka_consumer_group_exporter_lag{partition="17"} 1.0
kafka_consumer_group_exporter_lag{partition="19"} 1.0
kafka_consumer_group_exporter_lag{partition="20"} 1.0
kafka_consumer_group_exporter_lag{partition="28"} 1.0
kafka_consumer_group_exporter_lag{partition="30"} 0.0
kafka_consumer_group_exporter_lag{partition="32"} 0.0
kafka_consumer_group_exporter_lag{partition="33"} 1.0
kafka_consumer_group_exporter_lag{partition="43"} 0.0
```

Also values here look suspicious

**Comment by simPod** [comment]
When I used `-s`, some metrics started appearing, maybe it's somehow related to https://github.com/braedon/prometheus-kafka-consumer-group-exporter/issues/19

But even though the exporter's lag reached zero, some groups are not getting reported/getting invalid numbers. Is there a way I can somehow reset it?

**Comment by braedon** [comment]
Hi @simPod, `kafka_consumer_group_lag` and `kafka_consumer_group_exporter_lag` are different metrics.

`kafka_consumer_group_exporter_lag` shows the lag of the exporter itself in the `__consumer_offsets` topic, so the `group` and `topic` labels aren't relevant. Having low `kafka_consumer_group_exporter_lag` (like the 0 or 1 you're seeing there) means the exporter is keeping up with the commits being written to `__consumer_offsets` (which is good/necessary).

`kafka_consumer_group_lag` is what you're after, but can only include the offsets the exporter has read from `__consumer_offsets`.

If you don't use `-s`, the exporter only reads new offsets your consumer groups commit to `__consumer_offsets` after it starts. Each consumer group will only show up in `kafka_consumer_group_lag` (and other topics) once they have committed their offsets at least once since the exporter has started.

If you do use `-s`, the exporter will read all the offsets _currently_ in `__consumer_offsets` when it starts up, before consuming new offsets as they come in as usual. This means that existing consumer groups will show in metrics even if they aren't actively committing.

However, note that Kafka doesn't keep offset commit messages in `__consumer_groups` forever. If a consumer group doesn't commit for a while, its offsets will expire out of the topic, and Kafka will 'forget' about them. A consumer group that has expired won't show up in the exporter metrics, even if `-s` is used, as it will no longer be in `__consumer_groups` at all.

Is it possible this is what has happened to the consumer groups you aren't seeing? Are those consumers actively running/committing? The length of time offsets are kept is configured by the `offsets.retention.minutes` Kafka broker setting. Prior to Kafka 2.0.0 this was only 1 day by default. From 2.0.0 onwards, this is 7 days by default.

**Comment by simPod** [comment]
Thanks for exhaustive response @braedon! However, those consumers are running and committing. It was working with kafka 2.0. We have 2.1 now but not sure if that might be the issue, guess not. 

If I use `-s`, only some groups show up with invalid numbers (that's understandable) but only for a while and then even those disappear. If I run without `-s` nothing shows up at all. But for example, I receive high and low watermarks.

**Comment by braedon** [comment]
Ahh, you're running 2.1? Judging from [this code](https://github.com/apache/kafka/blob/db338ef67c3162e5b64efdb1538bf56cc53ec28a/core/src/main/scala/kafka/coordinator/group/GroupMetadataManager.scala#L1121), it looks like they changed the format of `__consumer_offsets` messages to v3 in 2.1 - the exporter only supports versions 0 and 1 currently.

In previous exporter versions this would have resulted in exceptions being thrown, but the fix to another issue in https://github.com/braedon/prometheus-kafka-consumer-group-exporter/pull/26 will be effectively suppressing them.

I'll look at implementing the new versions in the next few days.

**Comment by simPod** [comment]
That would explain why 0.4 stopped working with exception being thrown :) Thanks for help!

**Comment by braedon** [comment]
@simPod I've got a fix for this released as `0.5.1rc1`. Would you be able to test it out and make sure it fixes your issue before I release the final `0.5.1`? Thanks!

**Comment by simPod** [comment]
@braedon yup, something is popping up in charts and looks real :)

![image](https://user-images.githubusercontent.com/327717/55965123-3e24b480-5c76-11e9-8777-feb30e36a391.png)

Thanks!

**Comment by braedon** [comment]
Released https://github.com/braedon/prometheus-kafka-consumer-group-exporter/releases/tag/0.5.1
