### ISSUE TITLE
kafka-python v1.4.5 drastically impacts consumer performance.

### ISSUE THREAD

**Issue by jutley** [braedon/prometheus-kafka-consumer-group-exporter#30]
I made an issue over in the kafka-python project about new versions causing the consumer to perform with only an eighth of the throughput. You can see the here:
https://github.com/dpkp/kafka-python/issues/1888

In our case, this is a big issue as the the latest versions of this project can no longer keep up with our `__consumer_offsets` topic in some clusters.

I think that this project should explicitly depend on kafka-python v1.4.4 until this is fixed.

**Comment by braedon** [comment]
Decided in https://github.com/braedon/prometheus-kafka-consumer-group-exporter/pull/31 not to hold back kafka-python for now, since the performance decrease in 1.4.5+ isn't expected to be problematic for most users.

Leaving this issue open until https://github.com/dpkp/kafka-python/issues/1888 is resolved.

If you're affected by this issue, please weigh in!

**Comment by jutley** [comment]
@braedon kafka-python 1.4.7 should be in a good state. Can we cut a new release of this project to update the dependency?

**Comment by braedon** [comment]
I've released [0.5.4](https://github.com/braedon/prometheus-kafka-consumer-group-exporter/releases/tag/0.5.4) with exclusions for kafka-python 1.4.5 and 1.4.6. The 0.5.4 docker tag has been built using kafka-python 1.4.7.
